import React from 'react';
import {api} from './api';

type ManagedDevice={id:string;hostname:string;status:string};
export function AgentManagementDialog({device,onClose}:{device:ManagedDevice;onClose:()=>void}){
 const [busy,setBusy]=React.useState(''),[error,setError]=React.useState(''),[recovery,setRecovery]=React.useState('');
 async function password(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),value=String(data.get('password')),confirmation=String(data.get('confirmation'));if(value!==confirmation){setError('Password confirmation does not match.');return}setBusy('password');setError('');try{const result=await api<{recovery_code:string}>(`/api/v1/agents/devices/${device.id}/maintenance-password`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:value})});setRecovery(result.recovery_code);form.reset()}catch(value){setError(value instanceof Error?value.message:'Unable to update password.')}finally{setBusy('')}}
 async function uninstall(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy('uninstall');setError('');try{await api(`/api/v1/agents/devices/${device.id}/commands/uninstall`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm_hostname:String(data.get('hostname')),reason:String(data.get('reason')||'')||null,remove_identity:true})});onClose()}catch(value){setError(value instanceof Error?value.message:'Unable to queue remote uninstall.')}finally{setBusy('')}}
 return <div className="modalBackdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className="snmpDialog agentManagementDialog" role="dialog" aria-modal="true"><div className="snmpDialogHead"><div><h2>Manage {device.hostname}</h2><p>Password changes sync securely with the Agent. Remote uninstall commands expire after 10 minutes.</p></div><button type="button" onClick={onClose} disabled={!!busy}>×</button></div>{error&&<p className="snmpFormError" role="alert">{error}</p>}{recovery&&<div className="recoveryCode"><strong>Save this recovery code now</strong><code>{recovery}</code><span>It is shown once and replaces the previous recovery code.</span></div>}<div className="managementGrid"><form onSubmit={password}><h3>Uninstall password</h3><label>New password<input name="password" type="password" minLength={14} maxLength={200} autoComplete="new-password" required/></label><label>Confirm password<input name="confirmation" type="password" minLength={14} maxLength={200} autoComplete="new-password" required/></label><button disabled={!!busy}>{busy==='password'?'Saving...':'Set / change password'}</button></form><form onSubmit={uninstall} className="dangerZone"><h3>Remote uninstall</h3><p>This restores the proxy baseline, removes both Agent services and deletes local identity.</p><label>Type hostname to confirm<input name="hostname" placeholder={device.hostname} required/></label><label>Reason<input name="reason" maxLength={200}/></label><button disabled={!!busy||device.status!=='online'}>{busy==='uninstall'?'Queuing...':'Queue remote uninstall'}</button>{device.status!=='online'&&<small>Device must reconnect before a short-lived command can be received.</small>}</form></div></section></div>
}
