import React from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const sections=['Dashboard','Devices','Live Traffic','Web Logs','Bandwidth','Policies','Web Filtering','Categories','Users','Groups','VLAN Policies','Firewall','Agents','Alerts','Reports','Audit Logs','System Settings'];
const metrics=[['Total devices','—'],['Online devices','—'],['Offline devices','—'],['Requests allowed','—'],['Requests blocked','—'],['Current bandwidth','—']];
function App(){
  const [active,setActive]=React.useState('Dashboard');
  return <div className="shell"><aside><div className="brand"><span>NS</span><div>NetSentinel<small>Secure Access</small></div></div><nav>{sections.map(s=><button className={active===s?'active':''} onClick={()=>setActive(s)} key={s}>{s}</button>)}</nav><div className="operator"><i>BA</i><div>Balaram<small>Super Admin</small></div></div></aside><main><header><div><p>Operations / {active}</p><h1>{active}</h1></div><div className="status"><span></span>Platform status</div></header>{active==='Dashboard'?<Dashboard/>:<Empty name={active}/>}</main></div>
}
function Dashboard(){return <><section className="notice"><div><strong>Foundation environment</strong><p>Connect the API and enroll agents to populate live operational data.</p></div><button>View system health</button></section><section className="metrics">{metrics.map(([name,value],i)=><article key={name}><p>{name}</p><h2>{value}</h2><small>{i<3?'Inventory service':'Awaiting telemetry'}</small></article>)}</section><section className="grid"><article className="panel wide"><div className="panelHead"><div><h3>Web request activity</h3><p>Allowed and blocked requests over time</p></div><select aria-label="Activity range"><option>Last 24 hours</option></select></div><div className="emptyChart"><span></span><p>Activity appears after proxy ingestion starts</p></div></article><article className="panel"><h3>Component health</h3>{['Management API','PostgreSQL','Redis','Proxy adapter','Agent service'].map((x,i)=><div className="health" key={x}><span className={i>2?'muted':''}></span>{x}<b>{i>2?'Not configured':'Checking'}</b></div>)}</article><article className="panel"><h3>Top bandwidth users</h3><div className="empty"><b>No usage data yet</b><p>Bandwidth rollups will appear here.</p></div></article><article className="panel"><h3>Recent alerts</h3><div className="empty"><b>No active alerts</b><p>Operational alerts are clear.</p></div></article></section></>}
function Empty({name}:{name:string}){return <section className="panel page"><div className="empty"><b>{name} module</b><p>This navigation surface is ready for its Phase 2 vertical slice.</p></div></section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
