"""Phase 1 foundation."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "0001_foundation"
down_revision = None

def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS telemetry")
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("password_hash", sa.Text(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("failed_logins", sa.Integer(), nullable=False, server_default="0"), sa.Column("locked_until", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("roles", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(100), nullable=False, unique=True))
    op.create_table("permissions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("code", sa.String(100), nullable=False, unique=True))
    op.create_table("user_roles", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("role_permissions", sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True), sa.Column("permission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("permissions.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("devices", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("device_identifier", sa.String(200), nullable=False, unique=True), sa.Column("hostname", sa.String(255), nullable=False), sa.Column("username", sa.String(255)), sa.Column("ip_address", postgresql.INET()), sa.Column("mac_address", postgresql.MACADDR()), sa.Column("os_name", sa.String(100)), sa.Column("os_version", sa.String(100)), sa.Column("agent_version", sa.String(50)), sa.Column("vlan", sa.String(100)), sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("last_seen", sa.DateTime(timezone=True)), sa.Column("last_heartbeat", sa.DateTime(timezone=True)), sa.Column("credential_revoked_at", sa.DateTime(timezone=True)), sa.Column("metadata", postgresql.JSONB(), nullable=False, server_default="{}"))
    op.create_index("ix_devices_last_heartbeat", "devices", ["last_heartbeat"])
    op.create_table("agent_enrollments", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("used_at", sa.DateTime(timezone=True)), sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("device_heartbeats", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("device_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("devices.id", ondelete="CASCADE"), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("sequence", sa.BigInteger(), nullable=False), sa.Column("payload", postgresql.JSONB(), nullable=False), sa.UniqueConstraint("device_id", "sequence"))
    op.create_table("policies", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(200), nullable=False, unique=True), sa.Column("default_action", sa.String(10), nullable=False), sa.Column("active_version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.CheckConstraint("default_action IN ('ALLOW','BLOCK')"))
    op.create_table("policy_rules", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("policy_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("policies.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("priority", sa.Integer(), nullable=False), sa.Column("action", sa.String(10), nullable=False), sa.Column("domain_pattern", sa.String(253), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.CheckConstraint("action IN ('ALLOW','BLOCK')"), sa.UniqueConstraint("policy_id", "version", "priority"))
    op.create_index("ix_policy_rules_lookup", "policy_rules", ["policy_id", "version", "enabled", "priority"])
    op.create_table("audit_events", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("actor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("action", sa.String(150), nullable=False), sa.Column("resource_type", sa.String(100), nullable=False), sa.Column("resource_id", sa.String(200)), sa.Column("source_ip", postgresql.INET()), sa.Column("previous_value", postgresql.JSONB()), sa.Column("new_value", postgresql.JSONB()), sa.Column("result", sa.String(30), nullable=False), sa.Column("request_id", sa.String(64), nullable=False))
    op.create_index("ix_audit_events_time", "audit_events", ["occurred_at"])
    op.create_table("proxy_events", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("device_id", postgresql.UUID(as_uuid=True)), sa.Column("user_id", postgresql.UUID(as_uuid=True)), sa.Column("hostname", sa.String(255)), sa.Column("source_ip", postgresql.INET()), sa.Column("domain", sa.String(253), nullable=False), sa.Column("url", sa.Text()), sa.Column("destination_ip", postgresql.INET()), sa.Column("protocol", sa.String(20), nullable=False), sa.Column("port", sa.Integer(), nullable=False), sa.Column("method", sa.String(20)), sa.Column("status_code", sa.Integer()), sa.Column("action", sa.String(10), nullable=False), sa.Column("policy_id", postgresql.UUID(as_uuid=True)), sa.Column("matched_rule_id", postgresql.UUID(as_uuid=True)), sa.Column("category", sa.String(100)), sa.Column("bytes_up", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("bytes_down", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("duration_ms", sa.BigInteger()), sa.Column("idempotency_key", sa.String(100), nullable=False), sa.PrimaryKeyConstraint("id", "occurred_at"), sa.UniqueConstraint("idempotency_key", "occurred_at"), schema="telemetry", postgresql_partition_by="RANGE (occurred_at)")
    op.execute("CREATE TABLE telemetry.proxy_events_default PARTITION OF telemetry.proxy_events DEFAULT")
    op.create_index("ix_proxy_events_domain_time", "proxy_events", ["domain", "occurred_at"], schema="telemetry")

def downgrade():
    op.drop_table("proxy_events", schema="telemetry")
    for table in ["audit_events", "policy_rules", "policies", "device_heartbeats", "agent_enrollments", "devices", "role_permissions", "user_roles", "permissions", "roles", "users"]: op.drop_table(table)
    op.execute("DROP SCHEMA IF EXISTS telemetry")
