"""Endpoint enrollment and current state."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0003_endpoint_enrollment"; down_revision="0002_durable_telemetry"
def upgrade():
    for name,column in [("agent_identity",sa.Column("agent_identity",postgresql.UUID(as_uuid=True),unique=True)),("credential_hash",sa.Column("credential_hash",sa.String(64))),("credential_version",sa.Column("credential_version",sa.Integer(),nullable=False,server_default="1")),("architecture",sa.Column("architecture",sa.String(30))),("boot_time",sa.Column("boot_time",sa.DateTime(timezone=True))),("uptime_seconds",sa.Column("uptime_seconds",sa.BigInteger())),("last_heartbeat_ip",sa.Column("last_heartbeat_ip",postgresql.INET())),("current_status",sa.Column("current_status",sa.String(10),nullable=False,server_default="OFFLINE")),("enrollment_state",sa.Column("enrollment_state",sa.String(20),nullable=False,server_default="ENROLLED")),("group_name",sa.Column("group_name",sa.String(100))),("department",sa.Column("department",sa.String(100)))]: op.add_column("devices",column)
    op.add_column("agent_enrollments",sa.Column("revoked_at",sa.DateTime(timezone=True))); op.add_column("agent_enrollments",sa.Column("max_uses",sa.Integer(),nullable=False,server_default="1")); op.add_column("agent_enrollments",sa.Column("use_count",sa.Integer(),nullable=False,server_default="0")); op.add_column("agent_enrollments",sa.Column("group_name",sa.String(100))); op.add_column("agent_enrollments",sa.Column("department",sa.String(100)))
    op.create_table("device_state_transitions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("device_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("devices.id",ondelete="CASCADE"),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("previous_status",sa.String(10),nullable=False),sa.Column("new_status",sa.String(10),nullable=False)); op.create_index("ix_device_transitions_device_time","device_state_transitions",["device_id","occurred_at"]); op.create_index("ix_devices_status_seen","devices",["current_status","last_seen"])
def downgrade(): pass
